# Look for the header file.
FIND_PATH(FCGIPP_INCLUDE_DIR NAMES fastcgi.h)

# Look for the library.
FIND_LIBRARY(FCGI_LIBRARY NAMES fcgi)
FIND_LIBRARY(FCGIPP_LIBRARY NAMES fcgi++)

# Handle the QUIETLY and REQUIRED arguments and set FCGIPP_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FCGIPP DEFAULT_MSG FCGI_LIBRARY FCGIPP_LIBRARY FCGIPP_INCLUDE_DIR)

# Copy the results to the output variables.
IF(FCGIPP_FOUND)
    SET(FCGIPP_LIBRARIES ${FCGI_LIBRARY} ${FCGIPP_LIBRARY})
    SET(FCGIPP_INCLUDE_DIRS ${FCGIPP_INCLUDE_DIR})
ELSE(FCGIPP_FOUND)
    SET(FCGIPP_LIBRARIES)
    SET(FCGIPP_INCLUDE_DIRS)
ENDIF(FCGIPP_FOUND)

MARK_AS_ADVANCED(FCGIPP_INCLUDE_DIR FCGI_LIBRARY FCGIPP_LIBRARY)
