name: Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq libfcgi-dev libsqlite3-dev libcppunit-dev
    - name: Build
      run: |
        mkdir ../build
        cd ../build
        cmake ../insurlt -DBUILD_TESTS:BOOL=on
        make -j2
    - name: Run tests
      run: ../build/tests
